"""
04_ship_mode_analysis.py
--------------------------
Phase 4 - Ship Mode Performance Analysis
Project: Factory-to-Customer Shipping Route Efficiency Analysis
         for Nassau Candy Distributor

Input  : featured_nassau_candy.csv  (output of 02_feature_engineering.py)
Output : EDA_Charts/      (ship-mode visualizations)
         EDA_Summaries/   (ship_mode_summary.csv + supporting tables)

Run after 01_data_cleaning.py and 02_feature_engineering.py.
"""

import os
import warnings

import numpy as np
import pandas as pd
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import matplotlib.ticker as mticker
import seaborn as sns
from scipy import stats

warnings.filterwarnings("ignore")

# ─────────────────────────────────────────────────────────────
# GLOBAL STYLE
# ─────────────────────────────────────────────────────────────
sns.set_theme(style="whitegrid", palette="muted")
plt.rcParams.update({
    "figure.dpi": 150,
    "savefig.dpi": 300,
    "figure.figsize": (12, 6),
    "axes.titlesize": 14,
    "axes.labelsize": 12,
    "xtick.labelsize": 10,
    "ytick.labelsize": 10,
    "legend.fontsize": 10,
    "font.family": "DejaVu Sans",
})

PALETTE_CAT = "Set2"
ACCENT_COLOR = "#2C7BB6"
SHIP_MODE_ORDER = ["Same Day", "First Class", "Second Class", "Standard Class"]

# ─────────────────────────────────────────────────────────────
# PATHS
# ─────────────────────────────────────────────────────────────
IN_PATH = "featured_nassau_candy.csv"
CHARTS_DIR = "EDA_Charts"
SUMMARIES_DIR = "EDA_Summaries"
os.makedirs(CHARTS_DIR, exist_ok=True)
os.makedirs(SUMMARIES_DIR, exist_ok=True)

LEAD_TIME_COL = "Shipping Lead Time (Simulated)"

# ─────────────────────────────────────────────────────────────
# COUNTERS
# ─────────────────────────────────────────────────────────────
chart_count = 0
summary_count = 0
insight_list = []
report_count = 0  # NEW: tracks .txt reports generated by the extended steps


# ════════════════════════════════════════════════════════════════
# HELPER FUNCTIONS
# ════════════════════════════════════════════════════════════════

def save_chart(filename: str) -> None:
    """Save current matplotlib figure to EDA_Charts/ and close it."""
    global chart_count
    path = os.path.join(CHARTS_DIR, filename)
    plt.tight_layout()
    plt.savefig(path, dpi=300, bbox_inches="tight")
    plt.close()
    chart_count += 1
    print(f"  [Chart saved] {path}")


def save_summary(data: pd.DataFrame, filename: str) -> None:
    """Save a DataFrame to EDA_Summaries/ as CSV."""
    global summary_count
    path = os.path.join(SUMMARIES_DIR, filename)
    data.to_csv(path, index=False, float_format="%.2f")
    summary_count += 1
    print(f"  [Summary saved] {path}")


def save_report_text(text: str, filename: str) -> None:
    """Save a plain-text business/executive report to EDA_Summaries/."""
    global report_count
    path = os.path.join(SUMMARIES_DIR, filename)
    try:
        with open(path, "w", encoding="utf-8") as report_file:
            report_file.write(text)
        report_count += 1
        print(f"  [Report saved] {path}")
    except OSError as exc:
        print(f"  WARNING: Failed to save report '{filename}': {exc}")


def add_insight(text: str) -> None:
    """Append a business insight to the global list and print it."""
    insight_list.append(text)
    print(f"  [Insight {len(insight_list):02d}] {text}")


def fmt_currency(val: float) -> str:
    """Format a float as $X,XXX.XX."""
    return f"${val:,.2f}"


def order_ship_modes(values) -> list:
    """Return ship mode values ordered Same Day -> Standard Class,
    keeping any unexpected categories at the end."""
    values = list(values)  # avoid pandas Series "in" matching on index
    known = [m for m in SHIP_MODE_ORDER if m in values]
    extra = [m for m in values if m not in SHIP_MODE_ORDER]
    return known + extra


# ════════════════════════════════════════════════════════════════
# STEP 1 — LOAD DATASET
# ════════════════════════════════════════════════════════════════

def step1_load_dataset(path: str = IN_PATH) -> pd.DataFrame:
    """Load the featured dataset and display structural information."""
    print("\n" + "=" * 60)
    print("STEP 1: Load Dataset")
    print("=" * 60)

    try:
        data = pd.read_csv(path, low_memory=False)
    except FileNotFoundError as exc:
        raise FileNotFoundError(
            f"'{path}' not found. Run 01_data_cleaning.py and "
            "02_feature_engineering.py first."
        ) from exc

    required_cols = [
        "Ship Mode", "Sales", "Gross Profit", "Profit Margin %",
        LEAD_TIME_COL, "Delay Status", "Order ID",
    ]
    missing_cols = [c for c in required_cols if c not in data.columns]
    if missing_cols:
        raise KeyError(
            f"Required column(s) missing from '{path}': {missing_cols}. "
            "Please re-run 02_feature_engineering.py."
        )

    print(f"Dataset Shape     : {data.shape}")
    print(f"Number of Rows    : {data.shape[0]:,}")
    print(f"Number of Columns : {data.shape[1]}")
    print(f"Ship Modes Found  : {sorted(data['Ship Mode'].unique())}")

    return data


# ════════════════════════════════════════════════════════════════
# STEP 2 — BUILD CORE SHIP MODE SUMMARY
# ════════════════════════════════════════════════════════════════

def step2_build_ship_mode_summary(data: pd.DataFrame) -> pd.DataFrame:
    """
    Calculate, per Ship Mode:
      Total Shipments, Total Sales, Total Gross Profit,
      Average Shipping Lead Time, Average Profit Margin,
      Delay Rate %, On-Time Rate %, Moderate Delay %, Delayed %.
    """
    print("\n" + "=" * 60)
    print("STEP 2: Ship Mode Summary Table")
    print("=" * 60)

    summary = (
        data.groupby("Ship Mode")
        .agg(
            Total_Shipments=("Order ID", "count"),
            Total_Sales=("Sales", "sum"),
            Total_Gross_Profit=("Gross Profit", "sum"),
            Average_Lead_Time=(LEAD_TIME_COL, "mean"),
            Average_Profit_Margin=("Profit Margin %", "mean"),
        )
        .round(2)
        .reset_index()
    )

    # ── Delay Status breakdown (On Time / Moderate Delay / Delayed) ──
    if "Delay Status" in data.columns:
        status_counts = (
            data.groupby(["Ship Mode", "Delay Status"])
            .size()
            .unstack(fill_value=0)
        )
        status_pct = status_counts.div(status_counts.sum(axis=1), axis=0).mul(100).round(2)

        for status in ["On Time", "Moderate Delay", "Delayed"]:
            if status not in status_pct.columns:
                status_pct[status] = 0.0

        status_pct = status_pct.rename(columns={
            "On Time": "On_Time_Rate_%",
            "Moderate Delay": "Moderate_Delay_%",
            "Delayed": "Delay_Rate_%",
        }).reset_index()

        summary = summary.merge(
            status_pct[["Ship Mode", "On_Time_Rate_%", "Moderate_Delay_%", "Delay_Rate_%"]],
            on="Ship Mode", how="left",
        )
    else:
        summary["On_Time_Rate_%"] = np.nan
        summary["Moderate_Delay_%"] = np.nan
        summary["Delay_Rate_%"] = np.nan

    summary = summary.fillna(0)

    # Order rows logically: Same Day -> First -> Second -> Standard
    summary["Ship Mode"] = pd.Categorical(
        summary["Ship Mode"], categories=order_ship_modes(summary["Ship Mode"]), ordered=True
    )
    summary = summary.sort_values("Ship Mode").reset_index(drop=True)

    save_summary(summary, "ship_mode_summary.csv")
    print(summary.to_string(index=False))

    return summary


# ════════════════════════════════════════════════════════════════
# STEP 3 — ROUTE EFFICIENCY SCORE BY SHIP MODE
# ════════════════════════════════════════════════════════════════

def step3_route_efficiency_by_mode(data: pd.DataFrame) -> pd.DataFrame:
    """Build the Route Efficiency Score distribution (%) for each Ship Mode."""
    print("\n" + "=" * 60)
    print("STEP 3: Route Efficiency Score by Ship Mode")
    print("=" * 60)

    if "Route Efficiency Score" not in data.columns:
        print("  Route Efficiency Score column not found - skipping.")
        return pd.DataFrame()

    counts = (
        data.groupby(["Ship Mode", "Route Efficiency Score"])
        .size()
        .unstack(fill_value=0)
    )
    pct = counts.div(counts.sum(axis=1), axis=0).mul(100).round(2).reset_index()

    save_summary(pct, "ship_mode_route_efficiency.csv")
    print(pct.to_string(index=False))

    return pct


# ════════════════════════════════════════════════════════════════
# STEP 4 — COMPARISON TABLE (Sales / Profit / Lead Time / Delay / Efficiency)
# ════════════════════════════════════════════════════════════════

def step4_comparison_table(summary: pd.DataFrame, efficiency: pd.DataFrame) -> pd.DataFrame:
    """Combine core KPIs with Route Efficiency Score distribution for an
    at-a-glance comparison table across all Ship Modes."""
    print("\n" + "=" * 60)
    print("STEP 4: Ship Mode Comparison Table")
    print("=" * 60)

    comparison = summary.copy()
    if not efficiency.empty:
        comparison = comparison.merge(efficiency, on="Ship Mode", how="left")

    save_summary(comparison, "ship_mode_comparison.csv")
    print(comparison.to_string(index=False))

    return comparison


# ════════════════════════════════════════════════════════════════
# STEP 5 — VISUALIZATION: SALES BY SHIP MODE (BAR CHART)
# ════════════════════════════════════════════════════════════════

def step5_chart_sales(summary: pd.DataFrame) -> None:
    """Bar chart of Total Sales by Ship Mode."""
    print("\n" + "=" * 60)
    print("STEP 5: Chart - Sales by Ship Mode")
    print("=" * 60)

    fig, ax = plt.subplots(figsize=(10, 6))
    sns.barplot(
        data=summary, x="Ship Mode", y="Total_Sales",
        palette=PALETTE_CAT, ax=ax,
    )
    ax.set_title("Total Sales by Ship Mode", fontweight="bold")
    ax.set_xlabel("Ship Mode")
    ax.set_ylabel("Total Sales ($)")
    ax.yaxis.set_major_formatter(mticker.FuncFormatter(lambda x, _: f"${x:,.0f}"))

    for p in ax.patches:
        height = p.get_height()
        ax.annotate(
            f"${height:,.0f}", (p.get_x() + p.get_width() / 2, height),
            ha="center", va="bottom", fontsize=9,
        )

    save_chart("04_shipmode_sales_bar.png")


# ════════════════════════════════════════════════════════════════
# STEP 6 — VISUALIZATION: PROFIT BY SHIP MODE (BAR CHART)
# ════════════════════════════════════════════════════════════════

def step6_chart_profit(summary: pd.DataFrame) -> None:
    """Bar chart of Total Gross Profit by Ship Mode."""
    print("\n" + "=" * 60)
    print("STEP 6: Chart - Profit by Ship Mode")
    print("=" * 60)

    fig, ax = plt.subplots(figsize=(10, 6))
    sns.barplot(
        data=summary, x="Ship Mode", y="Total_Gross_Profit",
        palette="Greens_d", ax=ax,
    )
    ax.set_title("Total Gross Profit by Ship Mode", fontweight="bold")
    ax.set_xlabel("Ship Mode")
    ax.set_ylabel("Total Gross Profit ($)")
    ax.yaxis.set_major_formatter(mticker.FuncFormatter(lambda x, _: f"${x:,.0f}"))

    for p in ax.patches:
        height = p.get_height()
        ax.annotate(
            f"${height:,.0f}", (p.get_x() + p.get_width() / 2, height),
            ha="center", va="bottom", fontsize=9,
        )

    save_chart("04_shipmode_profit_bar.png")


# ════════════════════════════════════════════════════════════════
# STEP 7 — VISUALIZATION: DELAY STATUS (STACKED BAR CHART)
# ════════════════════════════════════════════════════════════════

def step7_chart_delay_stacked(data: pd.DataFrame) -> None:
    """Stacked bar chart of Delay Status counts by Ship Mode."""
    print("\n" + "=" * 60)
    print("STEP 7: Chart - Delay Status (Stacked Bar)")
    print("=" * 60)

    if "Delay Status" not in data.columns:
        print("  Delay Status column not found - skipping.")
        return

    pivot = (
        data.groupby(["Ship Mode", "Delay Status"])
        .size()
        .unstack(fill_value=0)
        .reindex(order_ship_modes(data["Ship Mode"].unique()))
    )

    status_colors = {
        "On Time": "#2ECC71",
        "Moderate Delay": "#F1C40F",
        "Delayed": "#E74C3C",
    }
    colors = [status_colors.get(c, "#95A5A6") for c in pivot.columns]

    ax = pivot.plot(
        kind="bar", stacked=True, color=colors,
        figsize=(11, 6), edgecolor="white",
    )
    ax.set_title("Delay Status Distribution by Ship Mode", fontweight="bold")
    ax.set_xlabel("Ship Mode")
    ax.set_ylabel("Order Count")
    ax.tick_params(axis="x", rotation=20)
    ax.legend(title="Delay Status")

    save_chart("04_shipmode_delay_stacked.png")


# ════════════════════════════════════════════════════════════════
# STEP 8 — VISUALIZATION: LEAD TIME (BOX PLOT)
# ════════════════════════════════════════════════════════════════

def step8_chart_lead_time_box(data: pd.DataFrame) -> None:
    """Box plot of Shipping Lead Time (Simulated) by Ship Mode."""
    print("\n" + "=" * 60)
    print("STEP 8: Chart - Lead Time (Box Plot)")
    print("=" * 60)

    fig, ax = plt.subplots(figsize=(10, 6))
    sns.boxplot(
        data=data, x="Ship Mode", y=LEAD_TIME_COL,
        order=order_ship_modes(data["Ship Mode"].unique()),
        palette=PALETTE_CAT, ax=ax,
    )
    ax.set_title("Shipping Lead Time Distribution by Ship Mode", fontweight="bold")
    ax.set_xlabel("Ship Mode")
    ax.set_ylabel("Lead Time (days, Simulated)")

    save_chart("04_shipmode_leadtime_box.png")


# ════════════════════════════════════════════════════════════════
# STEP 9 — VISUALIZATION: SHIPMENT DISTRIBUTION (PIE CHART)
# ════════════════════════════════════════════════════════════════

def step9_chart_pie(summary: pd.DataFrame) -> None:
    """Pie chart of shipment volume share by Ship Mode."""
    print("\n" + "=" * 60)
    print("STEP 9: Chart - Shipment Distribution (Pie)")
    print("=" * 60)

    fig, ax = plt.subplots(figsize=(7, 7))
    ax.pie(
        summary["Total_Shipments"],
        labels=summary["Ship Mode"],
        autopct="%1.1f%%",
        colors=sns.color_palette(PALETTE_CAT, len(summary)),
        startangle=140,
    )
    ax.set_title("Shipment Volume Share by Ship Mode", fontweight="bold")

    save_chart("04_shipmode_pie.png")


# ════════════════════════════════════════════════════════════════
# STEP 10 — VISUALIZATION: SHIP MODE vs DELAY STATUS (HEATMAP)
# ════════════════════════════════════════════════════════════════

def step10_chart_heatmap(data: pd.DataFrame) -> None:
    """Heatmap showing % of orders per Delay Status for each Ship Mode."""
    print("\n" + "=" * 60)
    print("STEP 10: Chart - Ship Mode vs Delay Status (Heatmap)")
    print("=" * 60)

    if "Delay Status" not in data.columns:
        print("  Delay Status column not found - skipping.")
        return

    pivot = (
        data.groupby(["Ship Mode", "Delay Status"])
        .size()
        .unstack(fill_value=0)
    )
    pivot_pct = pivot.div(pivot.sum(axis=1), axis=0).mul(100).round(1)
    pivot_pct = pivot_pct.reindex(order_ship_modes(pivot_pct.index))

    fig, ax = plt.subplots(figsize=(9, 6))
    sns.heatmap(
        pivot_pct, annot=True, fmt=".1f", cmap="YlOrRd",
        linewidths=0.5, linecolor="white", cbar_kws={"label": "% of Shipments"},
        ax=ax,
    )
    ax.set_title("Ship Mode vs Delay Status (% of Shipments)", fontweight="bold")
    ax.set_xlabel("Delay Status")
    ax.set_ylabel("Ship Mode")

    save_chart("04_shipmode_delay_heatmap.png")


# ════════════════════════════════════════════════════════════════
# STEP 11 — VISUALIZATION: AVERAGE LEAD TIME (LINE CHART)
# ════════════════════════════════════════════════════════════════

def step11_chart_lead_time_line(summary: pd.DataFrame) -> None:
    """Line chart of Average Shipping Lead Time across Ship Modes."""
    print("\n" + "=" * 60)
    print("STEP 11: Chart - Average Lead Time (Line)")
    print("=" * 60)

    ordered_summary = summary.set_index("Ship Mode").reindex(
        order_ship_modes(summary["Ship Mode"])
    ).reset_index()

    fig, ax = plt.subplots(figsize=(10, 6))
    ax.plot(
        ordered_summary["Ship Mode"], ordered_summary["Average_Lead_Time"],
        marker="o", color=ACCENT_COLOR, linewidth=2.5, markersize=8,
    )
    for x, y in zip(ordered_summary["Ship Mode"], ordered_summary["Average_Lead_Time"]):
        ax.annotate(f"{y:.1f}d", (x, y), textcoords="offset points",
                    xytext=(0, 8), ha="center", fontsize=9)

    ax.set_title("Average Shipping Lead Time by Ship Mode", fontweight="bold")
    ax.set_xlabel("Ship Mode")
    ax.set_ylabel("Average Lead Time (days)")
    ax.grid(alpha=0.3)

    save_chart("04_shipmode_leadtime_line.png")


# ════════════════════════════════════════════════════════════════
# STEP 12 — VISUALIZATION: COUNT PLOT (ORDERS BY SHIP MODE)
# ════════════════════════════════════════════════════════════════

def step12_chart_countplot(data: pd.DataFrame) -> None:
    """Count plot of total orders by Ship Mode, split by Delay Status."""
    print("\n" + "=" * 60)
    print("STEP 12: Chart - Order Count Plot")
    print("=" * 60)

    fig, ax = plt.subplots(figsize=(11, 6))
    if "Delay Status" in data.columns:
        sns.countplot(
            data=data, x="Ship Mode", hue="Delay Status",
            order=order_ship_modes(data["Ship Mode"].unique()),
            palette=PALETTE_CAT, ax=ax,
        )
        ax.legend(title="Delay Status")
    else:
        sns.countplot(
            data=data, x="Ship Mode",
            order=order_ship_modes(data["Ship Mode"].unique()),
            palette=PALETTE_CAT, ax=ax,
        )

    ax.set_title("Order Count by Ship Mode", fontweight="bold")
    ax.set_xlabel("Ship Mode")
    ax.set_ylabel("Order Count")

    save_chart("04_shipmode_countplot.png")


# ════════════════════════════════════════════════════════════════
# STEP 13 — BUSINESS INSIGHTS & CONSOLE REPORT
# ════════════════════════════════════════════════════════════════

def step13_business_report(summary: pd.DataFrame) -> None:
    """Print a professional console report highlighting the best, fastest,
    most profitable and lowest-delay Ship Modes, plus key business insights."""
    print("\n" + "=" * 60)
    print("STEP 13: Ship Mode Performance Report")
    print("=" * 60)

    # ── Best Ship Mode (highest total sales) ─────────────────
    best_sales_row = summary.loc[summary["Total_Sales"].idxmax()]
    add_insight(
        f"Best Ship Mode by Sales: {best_sales_row['Ship Mode']} "
        f"({fmt_currency(best_sales_row['Total_Sales'])})"
    )

    # ── Fastest Ship Mode (lowest average lead time) ─────────
    fastest_row = summary.loc[summary["Average_Lead_Time"].idxmin()]
    add_insight(
        f"Fastest Ship Mode: {fastest_row['Ship Mode']} "
        f"({fastest_row['Average_Lead_Time']:.2f} days average lead time)"
    )

    # ── Highest Profit Ship Mode ──────────────────────────────
    profit_row = summary.loc[summary["Total_Gross_Profit"].idxmax()]
    add_insight(
        f"Highest Profit Ship Mode: {profit_row['Ship Mode']} "
        f"({fmt_currency(profit_row['Total_Gross_Profit'])})"
    )

    # ── Lowest Delay Ship Mode ────────────────────────────────
    if "Delay_Rate_%" in summary.columns:
        lowest_delay_row = summary.loc[summary["Delay_Rate_%"].idxmin()]
        add_insight(
            f"Lowest Delay Ship Mode: {lowest_delay_row['Ship Mode']} "
            f"({lowest_delay_row['Delay_Rate_%']:.2f}% delayed)"
        )
        highest_delay_row = summary.loc[summary["Delay_Rate_%"].idxmax()]
        add_insight(
            f"Highest Delay Ship Mode: {highest_delay_row['Ship Mode']} "
            f"({highest_delay_row['Delay_Rate_%']:.2f}% delayed)"
        )

    # ── Most used Ship Mode ───────────────────────────────────
    volume_row = summary.loc[summary["Total_Shipments"].idxmax()]
    total_shipments = summary["Total_Shipments"].sum()
    add_insight(
        f"Most Used Ship Mode: {volume_row['Ship Mode']} "
        f"({int(volume_row['Total_Shipments']):,} shipments = "
        f"{volume_row['Total_Shipments'] / total_shipments * 100:.1f}% of all orders)"
    )

    # ── Margin comparison ──────────────────────────────────────
    margin_row = summary.loc[summary["Average_Profit_Margin"].idxmax()]
    add_insight(
        f"Highest Average Profit Margin: {margin_row['Ship Mode']} "
        f"({margin_row['Average_Profit_Margin']:.2f}%)"
    )

    # ── On-time performance ─────────────────────────────────────
    if "On_Time_Rate_%" in summary.columns:
        ontime_row = summary.loc[summary["On_Time_Rate_%"].idxmax()]
        add_insight(
            f"Best On-Time Rate: {ontime_row['Ship Mode']} "
            f"({ontime_row['On_Time_Rate_%']:.2f}% on time)"
        )

    # ── Speed vs cost trade-off note ────────────────────────────
    if fastest_row["Ship Mode"] != best_sales_row["Ship Mode"]:
        add_insight(
            f"Trade-off identified: {fastest_row['Ship Mode']} is fastest, "
            f"while {best_sales_row['Ship Mode']} drives the most sales volume "
            "- indicating a speed vs. revenue concentration trade-off."
        )

    # ── Final formatted report block ────────────────────────────
    print("\n" + "-" * 60)
    print("EXECUTIVE SHIP MODE REPORT")
    print("-" * 60)
    print(f"  Best Ship Mode (Sales)        : {best_sales_row['Ship Mode']}")
    print(f"  Fastest Ship Mode             : {fastest_row['Ship Mode']}")
    print(f"  Highest Profit Ship Mode      : {profit_row['Ship Mode']}")
    if "Delay_Rate_%" in summary.columns:
        print(f"  Lowest Delay Ship Mode        : {lowest_delay_row['Ship Mode']}")
    print(f"  Most Used Ship Mode           : {volume_row['Ship Mode']}")
    print("-" * 60)

    insights_df = pd.DataFrame({
        "Insight #": range(1, len(insight_list) + 1),
        "Insight": insight_list,
    })
    save_summary(insights_df, "ship_mode_business_insights.csv")


# ════════════════════════════════════════════════════════════════
# STEP 14 — FINAL REPORT
# ════════════════════════════════════════════════════════════════

def step14_final_report() -> None:
    """Print final execution summary."""
    print("\n" + "=" * 60)
    print("STEP 14: Final Report")
    print("=" * 60)
    print(f"  Total Charts Generated      : {chart_count}")
    print(f"  Total Summary Tables Saved  : {summary_count}")
    print(f"  Total Business Insights     : {len(insight_list)}")
    print(f"  Charts saved in             : ./{CHARTS_DIR}/")
    print(f"  Summaries saved in          : ./{SUMMARIES_DIR}/")
    print("  Ship Mode Analysis Completed Successfully")
    print("=" * 60)


# ════════════════════════════════════════════════════════════════
# ════════════════════════════════════════════════════════════════
# EXTENSION MODULE — ADVANCED ANALYTICS (STEPS 15-24)
# Added on top of the original 14-step pipeline. Nothing above this
# block was modified; all new logic only ADDS capability.
# ════════════════════════════════════════════════════════════════
# ════════════════════════════════════════════════════════════════

NUMERIC_CANDIDATE_COLS = [
    "Sales",
    "Gross Profit",
    "Profit Margin %",
    LEAD_TIME_COL,
    "Units",       # used as a stand-in for "Quantity" (column not present in this dataset)
    "Discount",    # included only if present in this dataset
]


# ════════════════════════════════════════════════════════════════
# STEP 15 — CORRELATION ANALYSIS
# ════════════════════════════════════════════════════════════════

def step15_correlation_analysis(data: pd.DataFrame) -> pd.DataFrame:
    """
    Build a correlation matrix for the key numeric columns (Sales,
    Gross Profit, Profit Margin %, Shipping Lead Time (Simulated),
    Units, Discount) and render it as a heatmap.

    Columns that do not exist in the current dataset (e.g. "Discount")
    are safely skipped rather than raising an error.
    """
    print("\n" + "=" * 60)
    print("STEP 15: Correlation Analysis")
    print("=" * 60)

    available_cols = [c for c in NUMERIC_CANDIDATE_COLS if c in data.columns]
    missing_cols = [c for c in NUMERIC_CANDIDATE_COLS if c not in data.columns]
    if missing_cols:
        print(f"  NOTE: columns not found and skipped: {missing_cols}")

    if len(available_cols) < 2:
        print("  WARNING: Not enough numeric columns available for correlation analysis.")
        return pd.DataFrame()

    try:
        corr_df = data[available_cols].apply(pd.to_numeric, errors="coerce").dropna()
        corr_matrix = corr_df.corr().round(3)
    except Exception as exc:
        print(f"  WARNING: Correlation computation failed: {exc}")
        return pd.DataFrame()

    save_summary(
        corr_matrix.reset_index().rename(columns={"index": "Column"}),
        "ship_mode_correlation_matrix.csv",
    )
    print(corr_matrix.to_string())

    fig, ax = plt.subplots(figsize=(9, 7))
    sns.heatmap(
        corr_matrix, annot=True, fmt=".2f", cmap="RdBu_r",
        center=0, square=True, linewidths=0.5, linecolor="white", ax=ax,
    )
    ax.set_title("Correlation Heatmap — Key Numeric Metrics", fontweight="bold")
    save_chart("04_correlation_heatmap.png")

    return corr_matrix


# ════════════════════════════════════════════════════════════════
# STEP 16 — STATISTICAL SUMMARY
# ════════════════════════════════════════════════════════════════

def step16_statistical_summary(data: pd.DataFrame) -> pd.DataFrame:
    """
    Compute Mean, Median, Std Dev, Min, Max, Q1, Q3 for Sales,
    Gross Profit and Shipping Lead Time (Simulated), broken down
    by Ship Mode.
    """
    print("\n" + "=" * 60)
    print("STEP 16: Statistical Summary")
    print("=" * 60)

    target_cols = ["Sales", "Gross Profit", LEAD_TIME_COL]
    target_cols = [c for c in target_cols if c in data.columns]

    if not target_cols:
        print("  WARNING: None of the target statistical columns were found.")
        return pd.DataFrame()

    stats_rows = []
    for ship_mode, group in data.groupby("Ship Mode"):
        for col in target_cols:
            series = pd.to_numeric(group[col], errors="coerce").dropna()
            if series.empty:
                continue
            q1, q3 = series.quantile([0.25, 0.75])
            stats_rows.append({
                "Ship Mode": ship_mode,
                "Metric": col,
                "Mean": round(series.mean(), 2),
                "Median": round(series.median(), 2),
                "Std Dev": round(series.std(), 2),
                "Min": round(series.min(), 2),
                "Max": round(series.max(), 2),
                "Q1": round(q1, 2),
                "Q3": round(q3, 2),
            })

    stats_df = pd.DataFrame(stats_rows)
    stats_df["Ship Mode"] = pd.Categorical(
        stats_df["Ship Mode"], categories=order_ship_modes(stats_df["Ship Mode"]), ordered=True
    )
    stats_df = stats_df.sort_values(["Ship Mode", "Metric"]).reset_index(drop=True)

    save_summary(stats_df, "ship_mode_statistics.csv")
    print(stats_df.to_string(index=False))

    return stats_df


# ════════════════════════════════════════════════════════════════
# STEP 17 — OUTLIER DETECTION (IQR METHOD)
# ════════════════════════════════════════════════════════════════

def step17_outlier_detection(data: pd.DataFrame) -> pd.DataFrame:
    """
    Detect outliers using the IQR method (1.5x IQR fences) for
    Sales, Gross Profit and Shipping Lead Time (Simulated), and
    report the outlier count/percentage per Ship Mode.
    """
    print("\n" + "=" * 60)
    print("STEP 17: Outlier Detection (IQR Method)")
    print("=" * 60)

    target_cols = ["Sales", "Gross Profit", LEAD_TIME_COL]
    target_cols = [c for c in target_cols if c in data.columns]

    if not target_cols:
        print("  WARNING: None of the target outlier columns were found.")
        return pd.DataFrame()

    outlier_rows = []
    for col in target_cols:
        series = pd.to_numeric(data[col], errors="coerce")
        q1, q3 = series.quantile([0.25, 0.75])
        iqr = q3 - q1
        lower_fence = q1 - 1.5 * iqr
        upper_fence = q3 + 1.5 * iqr
        is_outlier = (series < lower_fence) | (series > upper_fence)

        temp = data.loc[series.notna()].copy()
        temp["__is_outlier__"] = is_outlier.loc[series.notna()]

        for ship_mode, group in temp.groupby("Ship Mode"):
            total = len(group)
            outliers = int(group["__is_outlier__"].sum())
            outlier_rows.append({
                "Ship Mode": ship_mode,
                "Column": col,
                "Lower Fence": round(lower_fence, 2),
                "Upper Fence": round(upper_fence, 2),
                "Total Records": total,
                "Outlier Count": outliers,
                "Outlier %": round(outliers / total * 100, 2) if total else 0.0,
            })

    outliers_df = pd.DataFrame(outlier_rows)
    outliers_df["Ship Mode"] = pd.Categorical(
        outliers_df["Ship Mode"], categories=order_ship_modes(outliers_df["Ship Mode"]), ordered=True
    )
    outliers_df = outliers_df.sort_values(["Column", "Ship Mode"]).reset_index(drop=True)

    save_summary(outliers_df, "ship_mode_outliers.csv")
    print(outliers_df.to_string(index=False))

    return outliers_df


# ════════════════════════════════════════════════════════════════
# STEP 18 — ANOVA TEST
# ════════════════════════════════════════════════════════════════

def step18_anova_test(data: pd.DataFrame) -> pd.DataFrame:
    """
    Perform a one-way ANOVA test to determine whether Ship Mode has
    a statistically significant effect on Sales, Gross Profit and
    Shipping Lead Time (Simulated).
    """
    print("\n" + "=" * 60)
    print("STEP 18: ANOVA Test (Ship Mode Effect)")
    print("=" * 60)

    target_cols = ["Sales", "Gross Profit", LEAD_TIME_COL]
    target_cols = [c for c in target_cols if c in data.columns]

    anova_rows = []
    for col in target_cols:
        try:
            groups = [
                pd.to_numeric(group[col], errors="coerce").dropna()
                for _, group in data.groupby("Ship Mode")
            ]
            groups = [g for g in groups if len(g) > 1]

            if len(groups) < 2:
                print(f"  WARNING: Not enough groups to run ANOVA for '{col}'.")
                continue

            f_stat, p_value = stats.f_oneway(*groups)
            significant = "Yes" if p_value < 0.05 else "No"

            anova_rows.append({
                "Metric": col,
                "F-Statistic": round(f_stat, 4),
                "P-Value": round(p_value, 6),
                "Significant (p<0.05)": significant,
            })
        except Exception as exc:
            print(f"  WARNING: ANOVA failed for '{col}': {exc}")

    anova_df = pd.DataFrame(anova_rows)
    save_summary(anova_df, "anova_results.csv")
    print(anova_df.to_string(index=False))

    for _, row in anova_df.iterrows():
        add_insight(
            f"ANOVA on {row['Metric']}: F={row['F-Statistic']}, "
            f"p={row['P-Value']} -> Ship Mode effect significant: "
            f"{row['Significant (p<0.05)']}"
        )

    return anova_df


# ════════════════════════════════════════════════════════════════
# STEP 19 — DELAY RISK SCORE
# ════════════════════════════════════════════════════════════════

def step19_delay_risk_score(summary: pd.DataFrame) -> pd.DataFrame:
    """
    Classify each Ship Mode into a Delay Risk category (Low / Medium /
    High) based on its Delay Rate (%).

    Thresholds: < 15% -> Low, 15-35% -> Medium, > 35% -> High.
    """
    print("\n" + "=" * 60)
    print("STEP 19: Delay Risk Score")
    print("=" * 60)

    if "Delay_Rate_%" not in summary.columns:
        print("  WARNING: Delay_Rate_% column not found - skipping.")
        return pd.DataFrame()

    def classify_risk(delay_rate: float) -> str:
        if pd.isna(delay_rate):
            return "Unknown"
        if delay_rate < 15:
            return "Low"
        if delay_rate <= 35:
            return "Medium"
        return "High"

    risk_df = summary[["Ship Mode", "Delay_Rate_%"]].copy()
    risk_df["Delay Risk Score"] = risk_df["Delay_Rate_%"].apply(classify_risk)
    risk_df = risk_df.sort_values("Delay_Rate_%", ascending=False).reset_index(drop=True)

    save_summary(risk_df, "delay_risk_summary.csv")
    print(risk_df.to_string(index=False))

    high_risk = risk_df.loc[risk_df["Delay Risk Score"] == "High", "Ship Mode"].tolist()
    if high_risk:
        add_insight(f"High Delay Risk Ship Mode(s): {', '.join(high_risk)}")

    return risk_df


# ════════════════════════════════════════════════════════════════
# STEP 20 — SHIP MODE RANKING
# ════════════════════════════════════════════════════════════════

def step20_ship_mode_ranking(summary: pd.DataFrame) -> pd.DataFrame:
    """
    Rank Ship Modes on Sales, Profit, Lead Time and Delay Rate, then
    derive an Overall Rank from the average of the individual ranks
    (lower Overall Rank = better all-round performance).
    """
    print("\n" + "=" * 60)
    print("STEP 20: Ship Mode Ranking")
    print("=" * 60)

    ranking = summary[["Ship Mode"]].copy()

    ranking["Sales Rank"] = summary["Total_Sales"].rank(ascending=False, method="min").astype(int)
    ranking["Profit Rank"] = summary["Total_Gross_Profit"].rank(ascending=False, method="min").astype(int)
    ranking["Lead Time Rank"] = summary["Average_Lead_Time"].rank(ascending=True, method="min").astype(int)

    if "Delay_Rate_%" in summary.columns:
        ranking["Delay Rank"] = summary["Delay_Rate_%"].rank(ascending=True, method="min").astype(int)
        rank_cols = ["Sales Rank", "Profit Rank", "Lead Time Rank", "Delay Rank"]
    else:
        rank_cols = ["Sales Rank", "Profit Rank", "Lead Time Rank"]

    ranking["Overall Rank"] = (
        ranking[rank_cols].mean(axis=1).rank(ascending=True, method="min").astype(int)
    )
    ranking = ranking.sort_values("Overall Rank").reset_index(drop=True)

    save_summary(ranking, "ship_mode_ranking.csv")
    print(ranking.to_string(index=False))

    top_mode = ranking.loc[ranking["Overall Rank"].idxmin(), "Ship Mode"]
    add_insight(f"Overall Best-Ranked Ship Mode (composite score): {top_mode}")

    return ranking


# ════════════════════════════════════════════════════════════════
# STEP 21 — CONSOLIDATED KPI SUMMARY TABLE
# ════════════════════════════════════════════════════════════════

def step21_kpi_summary(summary: pd.DataFrame,
                        efficiency: pd.DataFrame,
                        ranking: pd.DataFrame) -> pd.DataFrame:
    """
    Build a single consolidated KPI table containing Ship Mode,
    Total Shipments, Total Sales, Total Gross Profit, Average Lead
    Time, Average Profit Margin, Delay Rate, Route Efficiency and
    Overall Rank.
    """
    print("\n" + "=" * 60)
    print("STEP 21: Consolidated KPI Summary Table")
    print("=" * 60)

    kpi = summary[[
        "Ship Mode", "Total_Shipments", "Total_Sales", "Total_Gross_Profit",
        "Average_Lead_Time", "Average_Profit_Margin",
    ]].copy()

    if "Delay_Rate_%" in summary.columns:
        kpi = kpi.merge(summary[["Ship Mode", "Delay_Rate_%"]], on="Ship Mode", how="left")
    else:
        kpi["Delay_Rate_%"] = np.nan

    # Route Efficiency: % of shipments classified as "Excellent" or "Good"
    if not efficiency.empty:
        good_cols = [c for c in ["Excellent", "Good"] if c in efficiency.columns]
        if good_cols:
            eff_score = efficiency[["Ship Mode"] + good_cols].copy()
            eff_score["Route_Efficiency_%"] = eff_score[good_cols].sum(axis=1).round(2)
            kpi = kpi.merge(eff_score[["Ship Mode", "Route_Efficiency_%"]], on="Ship Mode", how="left")
        else:
            kpi["Route_Efficiency_%"] = np.nan
    else:
        kpi["Route_Efficiency_%"] = np.nan

    if not ranking.empty:
        kpi = kpi.merge(ranking[["Ship Mode", "Overall Rank"]], on="Ship Mode", how="left")
    else:
        kpi["Overall Rank"] = np.nan

    kpi = kpi.rename(columns={
        "Total_Shipments": "Total Shipments",
        "Total_Sales": "Total Sales",
        "Total_Gross_Profit": "Total Gross Profit",
        "Average_Lead_Time": "Average Lead Time",
        "Average_Profit_Margin": "Average Profit Margin",
        "Delay_Rate_%": "Delay Rate %",
        "Route_Efficiency_%": "Route Efficiency %",
    })

    kpi = kpi.sort_values("Overall Rank").reset_index(drop=True)

    save_summary(kpi, "ship_mode_kpi_summary.csv")
    print(kpi.to_string(index=False))

    return kpi


# ════════════════════════════════════════════════════════════════
# STEP 22 — BUSINESS RECOMMENDATION ENGINE
# ════════════════════════════════════════════════════════════════

def step22_recommendation_engine(summary: pd.DataFrame,
                                  ranking: pd.DataFrame,
                                  risk_df: pd.DataFrame) -> str:
    """
    Automatically generate plain-language business recommendations
    based on the Ship Mode analysis (best/worst mode, delay reduction,
    profit improvement, route optimization).
    """
    print("\n" + "=" * 60)
    print("STEP 22: Business Recommendation Engine")
    print("=" * 60)

    recommendations = []

    try:
        if not ranking.empty:
            best_mode = ranking.iloc[0]["Ship Mode"]
            if "Delay Rank" in ranking.columns:
                worst_mode = ranking.sort_values(
                    ["Overall Rank", "Delay Rank"], ascending=[True, True]
                ).iloc[-1]["Ship Mode"]
            else:
                worst_mode = ranking.sort_values("Overall Rank", ascending=True).iloc[-1]["Ship Mode"]
            recommendations.append(
                f"1. Best Overall Ship Mode: '{best_mode}' delivers the strongest balance of "
                "sales, profit, speed and reliability. Prioritize this mode for high-value "
                "or time-sensitive shipments."
            )
            
            recommendations.append(
                f"2. Worst Overall Ship Mode: '{worst_mode}' ranks lowest across the composite "
                "KPI score. Review its cost structure, carrier performance, and routing logic."
            )

        if not risk_df.empty:
            high_risk_modes = risk_df.loc[risk_df["Delay Risk Score"] == "High", "Ship Mode"].tolist()
            if high_risk_modes:
                recommendations.append(
                    "3. Delay Reduction: " + ", ".join(high_risk_modes) +
                    " show High delay risk. Consider renegotiating carrier SLAs, adding buffer "
                    "capacity during peak periods, or shifting volume to faster alternatives."
                )
            else:
                recommendations.append(
                    "3. Delay Reduction: No Ship Mode currently falls into the High delay-risk "
                    "category; continue monitoring Delay Rate % monthly to catch early drift."
                )

        if "Average_Profit_Margin" in summary.columns:
            low_margin_row = summary.loc[summary["Average_Profit_Margin"].idxmin()]
            recommendations.append(
                f"4. Profit Improvement: '{low_margin_row['Ship Mode']}' has the lowest average "
                f"profit margin ({low_margin_row['Average_Profit_Margin']:.2f}%). Investigate "
                "cost-to-serve and consider targeted pricing or cost-reduction initiatives for "
                "this mode."
            )

        if "Average_Lead_Time" in summary.columns:
            slow_row = summary.loc[summary["Average_Lead_Time"].idxmax()]
            fast_row = summary.loc[summary["Average_Lead_Time"].idxmin()]
            recommendations.append(
                f"5. Route Optimization: '{slow_row['Ship Mode']}' has the longest average lead "
                f"time ({slow_row['Average_Lead_Time']:.2f} days) versus '{fast_row['Ship Mode']}' "
                f"at {fast_row['Average_Lead_Time']:.2f} days. Re-evaluate routing and carrier "
                "allocation on the slowest factory-to-state routes within this mode."
            )

        recommendations.append(
            "6. Capacity Planning: align fleet/carrier capacity with the highest-volume Ship "
            "Mode to avoid bottlenecks during demand spikes, while maintaining service levels "
            "on lower-volume, premium modes."
        )

    except Exception as exc:
        print(f"  WARNING: Recommendation generation encountered an issue: {exc}")

    report_text = "SHIP MODE BUSINESS RECOMMENDATIONS\n" + "=" * 60 + "\n\n"
    report_text += "\n\n".join(recommendations) + "\n"

    save_report_text(report_text, "ship_mode_recommendations.txt")
    for rec in recommendations:
        print(f"  {rec}\n")

    return report_text


# ════════════════════════════════════════════════════════════════
# STEP 23 — EXECUTIVE REPORT
# ════════════════════════════════════════════════════════════════

def step23_executive_report(summary: pd.DataFrame,
                             ranking: pd.DataFrame,
                             anova_df: pd.DataFrame,
                             recommendations_text: str) -> None:
    """
    Generate a professional executive-level text report summarizing
    the Ship Mode analysis: best/fastest/most profitable/lowest-delay
    modes, key findings, business recommendations, and a conclusion.
    """
    print("\n" + "=" * 60)
    print("STEP 23: Executive Report")
    print("=" * 60)

    try:
        best_sales_row = summary.loc[summary["Total_Sales"].idxmax()]
        fastest_row = summary.loc[summary["Average_Lead_Time"].idxmin()]
        profit_row = summary.loc[summary["Total_Gross_Profit"].idxmax()]

        lowest_delay_mode = "N/A"
        if "Delay_Rate_%" in summary.columns:
            lowest_delay_mode = summary.loc[summary["Delay_Rate_%"].idxmin(), "Ship Mode"]

        lines = []
        lines.append("EXECUTIVE REPORT — SHIP MODE PERFORMANCE")
        lines.append("Factory-to-Customer Shipping Route Efficiency Analysis")
        lines.append("Nassau Candy Distributor")
        lines.append("=" * 60)
        lines.append("")
        lines.append(f"Best Ship Mode (Sales)        : {best_sales_row['Ship Mode']}")
        lines.append(f"Fastest Ship Mode             : {fastest_row['Ship Mode']}")
        lines.append(f"Highest Profit Ship Mode      : {profit_row['Ship Mode']}")
        lines.append(f"Lowest Delay Ship Mode        : {lowest_delay_mode}")
        lines.append("")
        lines.append("KEY FINDINGS")
        lines.append("-" * 60)
        for insight in insight_list:
            lines.append(f"  - {insight}")

        if not anova_df.empty:
            lines.append("")
            lines.append("STATISTICAL SIGNIFICANCE (ANOVA)")
            lines.append("-" * 60)
            for _, row in anova_df.iterrows():
                lines.append(
                    f"  - {row['Metric']}: F={row['F-Statistic']}, p={row['P-Value']} "
                    f"(Significant: {row['Significant (p<0.05)']})"
                )

        if not ranking.empty:
            lines.append("")
            lines.append("OVERALL SHIP MODE RANKING")
            lines.append("-" * 60)
            for _, row in ranking.iterrows():
                lines.append(f"  Rank {int(row['Overall Rank'])}: {row['Ship Mode']}")

        lines.append("")
        lines.append("BUSINESS RECOMMENDATIONS")
        lines.append("-" * 60)
        lines.append(recommendations_text.split("=" * 60, 1)[-1].strip())

        lines.append("")
        lines.append("CONCLUSION")
        lines.append("-" * 60)
        lines.append(
            "Ship Mode is a material driver of shipping speed, cost and customer experience "
            "for Nassau Candy Distributor. Standardizing route assignment around the "
            "best-ranked Ship Mode, while actively managing delay risk on weaker modes, "
            "offers a clear, data-driven path to improving logistics efficiency and "
            "profitability nationwide."
        )

        report_text = "\n".join(lines) + "\n"
        save_report_text(report_text, "ship_mode_executive_report.txt")

    except Exception as exc:
        print(f"  WARNING: Executive report generation failed: {exc}")


# ════════════════════════════════════════════════════════════════
# STEP 24 — DASHBOARD-READY DATASET
# ════════════════════════════════════════════════════════════════

def step24_dashboard_dataset(data: pd.DataFrame, kpi: pd.DataFrame) -> pd.DataFrame:
    """
    Build a clean, lightweight dataset optimized for the Streamlit
    dashboard's Ship Mode Comparison module.
    """
    print("\n" + "=" * 60)
    print("STEP 24: Dashboard-Ready Dataset")
    print("=" * 60)

    dashboard_cols = [
        "Order ID", "Ship Mode", "Order Date", "Sales", "Gross Profit",
        "Profit Margin %", LEAD_TIME_COL, "Delay Status",
        "Route Efficiency Score", "State/Province", "Region", "Factory",
    ]
    dashboard_cols = [c for c in dashboard_cols if c in data.columns]

    try:
        dashboard_df = data[dashboard_cols].copy()
        dashboard_df = dashboard_df.dropna(subset=["Ship Mode"])

        save_summary(dashboard_df, "dashboard_ship_mode.csv")

        if not kpi.empty:
            save_summary(kpi, "dashboard_ship_mode_kpi.csv")

        print(f"  Dashboard dataset shape: {dashboard_df.shape}")
        print(f"  Columns included        : {dashboard_cols}")

    except Exception as exc:
        print(f"  WARNING: Dashboard dataset generation failed: {exc}")
        return pd.DataFrame()

    return dashboard_df


# ════════════════════════════════════════════════════════════════
# STEP 25 — EXTENDED FINAL REPORT
# ════════════════════════════════════════════════════════════════

def step25_extended_final_report() -> None:
    """
    Print an updated final execution summary that reflects all charts,
    summaries and text reports generated by both the original pipeline
    (Steps 1-14) and the new analytics extension (Steps 15-24).
    """
    print("\n" + "=" * 60)
    print("STEP 25: Extended Final Report")
    print("=" * 60)
    print(f"  Total Charts Generated      : {chart_count}")
    print(f"  Total Summary Tables Saved  : {summary_count}")
    print(f"  Total Text Reports Saved    : {report_count}")
    print(f"  Total Business Insights     : {len(insight_list)}")
    print(f"  Charts saved in             : ./{CHARTS_DIR}/")
    print(f"  Summaries & reports saved in: ./{SUMMARIES_DIR}/")
    print("  Advanced Ship Mode Analytics Completed Successfully")
    print("=" * 60)


# ════════════════════════════════════════════════════════════════
# MAIN PIPELINE
# ════════════════════════════════════════════════════════════════

def main() -> None:
    try:
        df = step1_load_dataset()

        summary = step2_build_ship_mode_summary(df)
        efficiency = step3_route_efficiency_by_mode(df)
        step4_comparison_table(summary, efficiency)

        step5_chart_sales(summary)
        step6_chart_profit(summary)
        step7_chart_delay_stacked(df)
        step8_chart_lead_time_box(df)
        step9_chart_pie(summary)
        step10_chart_heatmap(df)
        step11_chart_lead_time_line(summary)
        step12_chart_countplot(df)

        step13_business_report(summary)
        step14_final_report()

        # ── Advanced analytics extension (new) ───────────────────
        step15_correlation_analysis(df)
        step16_statistical_summary(df)
        step17_outlier_detection(df)
        anova_df = step18_anova_test(df)
        risk_df = step19_delay_risk_score(summary)
        ranking = step20_ship_mode_ranking(summary)
        kpi = step21_kpi_summary(summary, efficiency, ranking)
        recommendations_text = step22_recommendation_engine(summary, ranking, risk_df)
        step23_executive_report(summary, ranking, anova_df, recommendations_text)
        step24_dashboard_dataset(df, kpi)
        step25_extended_final_report()

    except Exception as exc:
        print(f"\nPIPELINE FAILED: {exc}")
        raise


if __name__ == "__main__":
    main()